<?php

/**
 * @file
 * Install, update and uninstall functions for the chriskinch_core module.
 */

/**
 * Install the CSS Inline module.
 */
function chriskinch_core_update_8000(){
	\Drupal::service('module_installer')->install(['css_inline', 'google_analytics']);
}

/**
 * Install the Honeypot module.
 */
function chriskinch_core_update_8001(){
	\Drupal::service('module_installer')->install(['honeypot']);
}